apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  type: NodePort
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      # Port on which the service is exposed within the cluster
      port: 80
      # Port on the container to forward traffic to
      targetPort: 3000
